export const SET_USER_DETAIL ="@USER_detail/SET_USER_DETAIL";

export const REQUEST_USER_SKILLS = "@USER/REQUEST_USER_SKILLS";

export const FAILED_USER_SKILLS = "@USER/FAILED_USER_SKILLS";

export const SUCCESS_USER_SKILLS ="@USER/SUCCESS_USER_SKILLS";